### ISSUE TITLE
The alert pops up before the final card's animation is complete

### ISSUE THREAD

**Issue by Abg4real** [gkanishk/GuessKaro#2]
Hi
I noticed an issue. The alert message pops up before the animation is complete.
Here is a screenshot.
![image](https://user-images.githubusercontent.com/55308761/96358931-388d1200-112a-11eb-9642-6b0b2c6584c8.png)
This also happens when we match two cards at any point. The message below the grid appears before the animation is complete.
Can you assign this to me?

**Comment by gkanishk** [comment]
Sure @Abg4real

**Comment by Abg4real** [comment]
I think we can safely mark this issue as resolved 😂
